name: Release

on:
  push:
    branches: [ "main" ] # Triggers on pushes to main
    tags: [ "v*" ] # Triggers on any tag with the prefix 'v'
  pull_request:
    branches: [ "main" ] # Triggers on pull requests

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        uses: crazy-max/ghaction-xgo@v3
        with:
          xgo_version: latest
          go_version: 1.22
          dest: bin
          prefix: kserver
          targets: windows/amd64,linux/amd64,linux/arm64,darwin/arm64
          v: false
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
          trimpath: true

      - name: Upload artifact # Always upload an artifact for possible debugging
        uses: actions/upload-artifact@v4
        with:
          name: kserver-${{ github.ref_name }}
          path: bin/kserver*

      - name: Release asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            bin/kserver*
          generate_release_notes: true
